// Stable error codes support the future upstream package-repair step.
window.errorDescriptions = {
  SCHEMA_INVALID:'The package does not match the v1 schema. Check required fields, field types, and unsupported settings.',
  FILE_MISSING:'A referenced file is missing. Ask the package creator to include it.',
  CHECKSUM_MISSING:'The package must include checksums.sha256.',
  CHECKSUM_FORMAT:'The checksum list is invalid or contains duplicate entries.',
  CHECKSUM_MISMATCH:'A file does not match its checksum. Regenerate the checksum list or obtain a fresh package.',
  CHECKSUM_INCOMPLETE:'The checksum list must cover every file except itself.',
  ZIP_INVALID:'The ZIP file could not be read. Obtain a fresh, unencrypted package.',
  ZIP_DUPLICATE:'The package contains conflicting file names.', ZIP_SYMLINK:'Symbolic links are not supported.', ZIP_ENCRYPTED:'Encrypted ZIP files are not supported.',
  ZIP_LIMIT:'The package exceeds the file-count or extraction-size limit.', ZIP_TOO_LARGE:'The compressed package must be smaller than 2 GB.',
  UNSAFE_PATH:'A package path contains unsupported characters or points outside the package.',
  JSON_INVALID:'A configuration file contains invalid JSON.', JSON_TOO_LARGE:'A configuration file is too large.',
  VIDEO_SIZE:'Use 1920 × 1080 or 1080 × 1920 at 30fps.', OUTPUT_NAME:'The output name must be a single .mp4 file name.',
  NARRATION_RANGE:'The narration range is outside the video timeline.', DUPLICATE_ID:'Scene and caption IDs must be unique.',
  TIMELINE_GAP:'Scenes must form a continuous timeline without gaps or overlaps.', TIMELINE_END:'The last scene must end at the declared total frame count.',
  TRANSITION_INVALID:'The transition is invalid. The first scene must use a cut.', SOURCE_RANGE:'The video source range must equal its timeline duration.',
  AUDIO_DISABLED_GAIN:'Disabled video audio must have a gain of zero.', AUDIO_OVERLAP:'Narration and enabled video audio cannot overlap.',
  BRAND_TYPE:'Intro and outro scenes must be video clips.', BRAND_REFERENCE:'Intro or outro scene references do not match the timeline.', BRAND_POSITION:'Intro and outro scenes must be at the beginning and end.',
  CAPTION_TEXT:'A caption contains empty text or unsupported control characters.', CAPTION_LINES:'Each caption must contain one or two non-empty lines.',
  CAPTION_TIME:'A caption overlaps another caption or falls outside the timeline.', CAPTION_BRAND_BOUNDARY:'A caption crosses an intro/body/outro boundary.',
  CAPTION_BOX:'The caption box is outside the video or its line height is too small.', CAPTION_OVERFLOW:'A caption does not fit inside the specified box. Fix wrapping or layout upstream.',
  CAPTION_LINE_HEIGHT:'The supplied font requires a larger line height.', FONT_FORMAT:'Supply a single TTF or OTF font, not a font collection.', FONT_GLYPH:'The font is missing one or more caption characters.',
  WATERMARK_RANGE:'The watermark timing or position is invalid.', WATERMARK_SIZE:'Use a PNG watermark that fits inside the frame.',
  AUDIO_FORMAT:'The final soundtrack must be PCM WAV, 48kHz, stereo.', AUDIO_DURATION:'The final soundtrack must match the complete timeline exactly. Prepare all audio joins and silence upstream.',
  MEDIA_DIMENSIONS:'An image or video has invalid or excessively large dimensions.', IMAGE_FORMAT:'Use PNG or JPEG images.', VIDEO_FORMAT:'Use H.264 MP4 video with a constant 30fps frame rate.',
  VIDEO_TOO_SHORT:'A source video is shorter than its requested trim range.', VIDEO_AUDIO:'An enabled video audio track is missing or too short.',
  MEDIA_PROCESS_FAILED:'A media file could not be decoded or processed. Review the diagnostic details.',
  CANCELLED:'Task cancelled. Your original package is unchanged.', WORKER_EXIT:'The render process stopped unexpectedly. Import the package again.',
  ENOSPC:'The disk is full. Free some space and retry.', EACCES:'The application cannot access a required file or output folder.', EPERM:'Access was denied. Choose a writable output folder.',
};
